name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: 'Check code quality'
      run: |
        sbt ';scalafixAll -check ;scalariformFormat ;test:scalariformFormat'
        
        git diff --exit-code || (
          echo "ERROR: Scalariform check failed, see differences above."
          echo "To fix, format your sources using ./build scalariformFormat test:scalariformFormat before submitting a pull request."
          echo "Additionally, please squash your commits (eg, use git commit --amend) if you're going to update this pull request."
          false
        )
        
        sbt scapegoat

    - name: Run tests
      run: sbt ';+core/testOnly ;^sbt-plugin/testOnly'
